# smartlight.yaml
apiVersion: extensions/v1beta1 
kind: Deployment 
metadata:
  name: smartlight
spec:
  replicas: 1 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0 
  minReadySeconds: 5
  template:
    metadata:
      labels:
        name: smartlight-server
    spec:
      containers:
      - name: smartlight 
        image: jojo13572001/smartlight
        ports:
        - containerPort: 80
---
apiVersion: v1 
kind: Service
metadata:
  name: smartlight 
  labels:
    name: smartlight-server 
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - name: port1
      port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    name: smartlight-server 
